import type { Metadata } from 'next';
import { Merriweather } from 'next/font/google';
import Navbarlinks from './navbarlinks';
import './globals.css';

const merriweather = Merriweather({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Snippet',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-offblack">
      <body className={`${merriweather.className} flex `}>
        <Navbarlinks />
        <div className=" flex-1 flex justify-center">{children}</div>
      </body>
    </html>
  );
}
