import type { Metadata } from 'next';
import { Merriweather } from 'next/font/google';
import Navbar from '../components/navbar';
import { auth } from '@/lib/auth';

import './globals.css';

const merriweather = Merriweather({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Snippet',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  const user = session ? session.user : null;

  return (
    <html lang="en" className="bg-offblack">
      <body
        className={`${merriweather.className} flex flex-col max-w-full h-screen `}
      >
        <Navbar user={user} />
        <div className=" flex self-center justify-center w-full h-full">
          {children}
        </div>
      </body>
    </html>
  );
}
