import type { Metadata } from 'next';
import { Merriweather } from 'next/font/google';
import { Nav } from '../components/nav';
import { ShoppingCart } from 'lucide-react';
import './globals.css';

const merriweather = Merriweather({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Snippet',
  description: 'Generated by create next app',
};

const links = [
  {
    title: '1',

    variant: 'ghost' as 'ghost',
  },
  {
    title: '1',

    variant: 'ghost' as 'ghost',
  },
  {
    title: '1',

    variant: 'ghost' as 'ghost',
  },
  {
    title: '1',

    variant: 'ghost' as 'ghost',
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-offblack">
      <body className={`${merriweather.className} flex `}>
        <Nav isCollapsed={true} links={links} />
        <div className=" flex-1 flex justify-center">{children}</div>
      </body>
    </html>
  );
}
